name: Update clash-nyanpasu-nightly (no persist)

on:
  schedule:
    - cron: "0 0 * * *"   # 每天凌晨跑一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your bucket
        uses: actions/checkout@v4

      - name: Download upstream manifest
        run: |
          curl -L "https://raw.githubusercontent.com/hoilc/scoop-lemon/refs/heads/master/bucket/clash-nyanpasu-nightly.json" -o clash.json

      - name: Remove persist
        run: |
          mkdir -p bucket
          # 使用 jq 删除 persist 字段
          jq 'del(.persist)' clash.json > bucket/clash-nyanpasu-nightly.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bucket/clash-nyanpasu-nightly.json
          git commit -m "auto: update clash-nyanpasu-nightly without persist" || echo "No changes to commit"
          git push
